INCLUDE FORTH-STRUCT.FS

STRUCTURE: \ DATE
  CELLFLD FIELDNAME DATE.YEAR
  CELLFLD FIELDNAME DATE.MONTH
  CELLFLD FIELDNAME DATE.DAY
 STRUCTSIZE  DATE.SIZE
 STRUCTALIGN DATE.ALIGN
 STRUCTEMBED DATE.FLD
;STRUCTURE

STRUCTURE: \ PERSON
  CHARFLD 10 ARRAYFLD  FIELDNAME PERSON.FIRST
  CHARFLD 20 ARRAYFLD  FIELDNAME PERSON.LAST
  DATE.FLD             FIELDNAME PERSON.DOB
 STRUCTSIZE  PERSON.SIZE
 STRUCTALIGN PERSON.ALIGN
 STRUCTEMBED PERSON.FLD
;STRUCTURE
