INCLUDE ../forth-struct.fs

STRUCTURE: \ DATE
  CELLFLD FIELDNAME DATE.YEAR
  CELLFLD FIELDNAME DATE.MONTH
  CELLFLD FIELDNAME DATE.DAY
 STRUCTSIZE  DATE.SIZE
 STRUCTALIGN DATE.ALIGN
 STRUCTEMBED DATE.FLD
;STRUCTURE

( year month day date -- )
: DATE.INIT
	>R
	R@ DATE.DAY !
	R@ DATE.MONTH !
	R> DATE.YEAR !
;

( -- )
: DATE.PRINTDELIM [CHAR] / EMIT SPACE ;

( date -- )
: DATE.PRINT
	>R
	R@ DATE.DAY @ .
	DATE.PRINTDELIM
	R@ DATE.MONTH @ .
	DATE.PRINTDELIM
	R> DATE.YEAR @ .
;

STRUCTURE: \ PERSON
  CHARFLD              FIELDNAME PERSON.FIRSTLEN
  CHARFLD 10 ARRAYFLD  FIELDNAME PERSON.FIRST
  CHARFLD              FIELDNAME PERSON.LASTLEN
  CHARFLD 20 ARRAYFLD  FIELDNAME PERSON.LAST
  DATE.FLD             FIELDNAME PERSON.BIRTH
  DATE.FLD             FIELDNAME PERSON.DEATH
 STRUCTSIZE  PERSON.SIZE
 STRUCTALIGN PERSON.ALIGN
 STRUCTEMBED PERSON.FLD
;STRUCTURE

( firstname namelen person -- )
: PERSON.FIRST= >R R@ PERSON.FIRST SWAP >R R@ MOVE R> R> PERSON.FIRSTLEN C! ;
( lastname namelen person -- )
: PERSON.LAST= >R R@ PERSON.LAST SWAP >R R@ MOVE R> R> PERSON.LASTLEN C! ;
( year month day person -- )
: PERSON.BIRTH= PERSON.BIRTH DATE.INIT ;
( year month day person -- )
: PERSON.DEATH= PERSON.DEATH DATE.INIT ;

( person -- )
: PERSON.PRINT
	>R
	R@ PERSON.FIRST R@ PERSON.FIRSTLEN C@ TYPE
	SPACE
	R@ PERSON.LAST R@ PERSON.LASTLEN C@ TYPE
	." , Born "
	R@ PERSON.BIRTH DATE.PRINT
	." , Died "
	R> PERSON.DEATH DATE.PRINT
;

PERSON.SIZE ALLOT HERE VARIABLE JOHN_SMITH
PERSON.SIZE ALLOT HERE VARIABLE HEATHER_FREDRICK

s" John"   JOHN_SMITH PERSON.FIRST=
s" Smith"  JOHN_SMITH PERSON.LAST=
1949 10 24 JOHN_SMITH PERSON.BIRTH=
1984  1 20 JOHN_SMITH PERSON.DEATH=
JOHN_SMITH PERSON.PRINT CR CR

s" Heather"  HEATHER_FREDRICK PERSON.FIRST=
s" Fredrick" HEATHER_FREDRICK PERSON.LAST=
1800  3 14   HEATHER_FREDRICK PERSON.BIRTH=
1890 11 30   HEATHER_FREDRICK PERSON.DEATH=
HEATHER_FREDRICK PERSON.PRINT CR CR
